# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'

# needed to install the magick and the sf packages
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'          # for magick
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable' # for sf
    packages:
      # magick
      - libmagick++-dev
      # sf
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
